# Generated by Django 4.1.4 on 2022-12-28 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=120, verbose_name='company')),
                ('phone', models.CharField(max_length=20, verbose_name='Contact Phone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='number')),
                ('description', models.CharField(max_length=1000, verbose_name='description')),
                ('status', models.CharField(max_length=120, verbose_name='status')),
            ],
        ),
        migrations.CreateModel(
            name='support_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('scope', models.CharField(max_length=120, verbose_name='scope')),
                ('manager', models.CharField(max_length=120, verbose_name='manager')),
                ('category', models.CharField(choices=[('Server', 'SERVER'), ('Client', 'CLIENT'), ('Hardware', 'HARDWARE'), ('Network', 'NETWORK')], max_length=120, verbose_name='category')),
                ('subcategory', models.CharField(choices=[('windows server', 'Windows server'), ('unix', 'Unix')], max_length=120, verbose_name='subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='number')),
                ('description', models.CharField(max_length=1000, verbose_name='description')),
                ('serial_number', models.CharField(max_length=1000, verbose_name='serial_number')),
                ('type', models.CharField(choices=[('incident', 'INCIDENT'), ('major', 'MAJOR')], max_length=120, verbose_name='type')),
                ('SLA', models.CharField(max_length=120, verbose_name='SLA')),
                ('assigned_to', models.CharField(max_length=20, verbose_name='Agent')),
                ('team', models.CharField(max_length=120, verbose_name='support_team')),
                ('status', models.CharField(max_length=120, verbose_name='status')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=120, verbose_name='position')),
                ('support_team', models.CharField(max_length=120, verbose_name='team')),
                ('phone', models.CharField(max_length=20, verbose_name='Contact Phone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
