# Generated by Django 4.1.4 on 2022-12-18 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('surname', models.CharField(max_length=120, verbose_name='surname')),
                ('position', models.CharField(max_length=120, verbose_name='position')),
                ('support_team', models.CharField(max_length=120, verbose_name='team')),
                ('phone', models.CharField(max_length=20, verbose_name='Contact Phone')),
                ('email_address', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
                ('pwd', models.CharField(max_length=20, verbose_name='password')),
            ],
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='support_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('scope', models.CharField(max_length=120, verbose_name='scope')),
                ('manager', models.CharField(max_length=120, verbose_name='manager')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='number')),
                ('description', models.CharField(max_length=120, verbose_name='description')),
                ('type', models.CharField(max_length=120, verbose_name='type')),
                ('SLA', models.CharField(max_length=120, verbose_name='SLA')),
                ('assigned_to', models.CharField(max_length=20, verbose_name='Agent')),
                ('team', models.CharField(max_length=120, verbose_name='support_team')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('surname', models.CharField(max_length=120, verbose_name='surname')),
                ('company', models.CharField(max_length=120, verbose_name='company')),
                ('phone', models.CharField(max_length=20, verbose_name='Contact Phone')),
                ('email_address', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
                ('pwd', models.CharField(max_length=20, verbose_name='password')),
            ],
        ),
    ]
