# Generated by Django 4.1.4 on 2022-12-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='comments',
            field=models.JSONField(verbose_name='comments'),
        ),
    ]
