# Generated by Django 4.1.4 on 2022-12-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='serial_number',
            new_name='serial_number_or_client_name',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='SLA',
            field=models.IntegerField(verbose_name='SLA'),
        ),
    ]
