# Generated by Django 4.1.4 on 2022-12-28 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0002_rename_serial_number_ticket_serial_number_or_client_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket_app.customer'),
        ),
    ]
