# Generated by Django 4.1.4 on 2022-12-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0002_alter_ticket_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='comments',
            field=models.JSONField(max_length=1000, verbose_name='comments'),
        ),
    ]
