# Generated by Django 4.1.4 on 2022-12-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0004_alter_ticket_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assigned_to',
            field=models.CharField(max_length=20, verbose_name='assigned_to'),
        ),
    ]
